export const createInitialCardRuntimeState = ({ singleViewPageId }) => ({
  _hass: null,
  _lastHassCameraStateSignature: "",
  _lastHassLinkedLightStateSignature: "",
  _lastHassThemeSignature: "",
  _lastHassReviewStatusSignature: "",
  _lastHaReviewStatusApplyAt: 0,
  _activeCameraAvailability: null,
  _config: null,
  _navigationFactory: null,
  _pageId: singleViewPageId,
  _lastNonPreviewPageId: singleViewPageId,
  _started: false,
  _activeCamIdx: 0,
  _activeGroupMemberOverride: "",
  _preservingLiveShell: false,
  _camCache: {},

  _viewMode: "single",
  _eventsMode: "camera",
  _events: [],
  _recordings: [],
  _reviews: [],
  _kept: [],
  _tab: "alerts",
  _lastNonControlsTab: "alerts",
  _mobileCamSwitcherOpen: false,
  _browseOpen: false,
  _winEnd: 0,
  _winStart: 0,
  _followNowWindow: true,
  _loading: false,
  _exhausted: false,
  _daysWithActivity: new Set(),
  _calendarActivityByCam: new Map(),
  _calendarActivityInFlight: new Map(),
  _filterLabel: "all",
  _filterZone: "all",
  _favOnly: false,
  _calMonth: null,
  _calSelectedDay: null,

  _engine: null,
  _gridEngine: null,
  _unsub: null,
  _rotateTimer: null,
  _cardWidth: 0,
  _playSeq: 0,
  _streamMuted: true,
  _activeStreamType: "--",
  _lastLiveStreamHint: "",
  _committedLiveAvailabilityEntity: "",
  _committedLiveAvailabilityEngine: null,

  _slideshowActive: false,
  _slideshowPausedUntil: 0,
  _slideshowPendingAlertCam: "",
  _slideshowPendingAlertType: "",
  _slideshowLastAlertAt: 0,
  _slideshowLastAlertCam: "",
  _slideshowAttentionType: "",
  _slideshowHandledReviewIds: new Set(),
  _slideshowStartedAtSec: 0,
  _slideshowReviewProbeT: null,
  _slideshowReviewWatchT: null,
  _slideshowReviewProbeInFlight: false,
  _slideshowSwitchT: null,
  _slideshowPauseT: null,
  _slideshowFadeT: null,
  _slideshowPopupPaused: false,
  _slideshowNextSwitchAtMs: 0,
  _slideshowCountdownT: null,

  _gridRotationStart: 0,
  _gridRotationT: null,
  _gridAlertReturnT: null,
  _gridRefreshT: null,
  _snapshotRefreshT: null,
  _gridResumePending: false,
  _gridPinnedRotationStart: 0,
  _gridLastRenderSignature: "",
  _gridActivationSeq: 0,

  _previewPageActive: false,
  _previewLastRenderSignature: "",
  _previewMediaState: null,
  _twoWayTalkSession: null,
  _twoWayTalkStarting: false,
  _twoWayTalkStartAbortController: null,
  _twoWayTalkStartSeq: 0,
  _twoWayTalkEntity: "",
  _twoWayTalkResultBubble: null,
  _twoWayTalkResultTimer: null,

  _domCache: {},
  _fallbackImgUrlCache: new Map(),
  _fallbackReqId: 0,
  _eventsLoadToken: 0,
  _reviewsLoadToken: 0,
  _windowLoadToken: 0,
  _warmCamsToken: 0,
  _warmReviewsToken: 0,
  _warmOtherCamsDelayT: null,
  _reloadPending: false,
  _reloadAfterLoad: false,
  _realtimeHeadPollT: null,
  _switchLoadT: null,
  _listScrollController: null,
  _liveControlsHideTimer: null,
  _liveOverlayControlsController: null,
  _lastLiveOverlayPointerType: "mouse",
  _recordingsDayRequestCache: new Map(),
  _recordingsNavUpdateToken: 0,
  _recordingsDayNavAnimating: false,
  _recordingsSwipeController: null,
  _mountSeq: 0,
  _lastRenderedListHtml: "",
  _pendingMountDestroyers: [],
  _pendingWebRTCTakeoverTimer: null,

  _wasVisible: false,
  _resumeLiveT: null,
  _editorLayoutSyncRaf: 0,
  _disconnectTeardownT: null,
  _dashboardLiveGraceActive: false,
  _lastLiveKick: 0,
  _rotateOverlayActive: false,
  _rotateOverlayMode: "none",
  _rotateLiveOverlayDismissed: false,
  _rotateOverlayRaf: 0,
  _rotateOverlayExitT: null,
  _rotateOverlaySyncVideo: null,
  _onRotateOverlayVolumeChange: null,
  _rotateStyledVideo: null,
  _rotateStyledVideoCssText: "",
  _engineMountedMuted: true,
  _mountInProgress: false,
  _mountStartedAt: 0,
  _mountTargetEntity: "",
  _mseConnectAt: 0,
  _mseLastChunkAt: 0,
  _mseChunkCount: 0,

  _deepLinkEventId: "",
  _deepLinkReviewId: "",
  _deepLinkMediaHint: "",
  _deepLinkCameraHint: "",
  _deepLinkApplied: false,
  _deepLinkEventLookupTried: false,
  _deepLinkReviewLookupTried: false,
  _committedConfig: null,
});
